### ISSUE TITLE
Tracking issue: internationalisation (a.k.a. i18n)

### ISSUE THREAD

**Issue by AltGr** [ocaml-sf/learn-ocaml#36]
- [x] Internationalisation of the interface (framework is here, only english and french at the moment; note: translations are not dynamic, i.e. they are built-in and fixed at compile-time rather than fetched dynamically. But that could be improved)
- [ ] Internationalisation of exercises
  - [x] Simple solution: duplicate the exercises files with language variants (`descr.en.html`, `descr.fr.html`...)
  - [ ] More comprehensive solution: avoid duplicating code between languages. Indeed, `template.ml` or others may contain strings; `test.ml` even generates reports that should probably be localised too. Some templating mechanism / inclusion of the ppx ? This is not easy to solve ; also, if we even want to localise values _names_, I think dumplication remains the better option.

**Comment by yurug** [comment]
Can you elaborate on the part "This is not easy to solve"?

Falling back to duplication would be unsatisfying.

I agree that the report messages too should be localized. We could provide a standard library of messages to minimize the translation work but in any case, we can reuse the same translation mechanism as in the interface, can't we?

For code identifiers, the story is different: code must be written in english.

**Comment by AltGr** [comment]
> For code identifiers, the story is different: code must be written in english.

Ok, that was my opinion too :)

> Can you elaborate on the part "This is not easy to solve"?

Maybe I should just have said "this is non-trivial" ;). See the difficulties and possible solutions below:

Translation for the interface is done at the app level: a ppx enables us to gather all strings marked for translation, and rewrites them into a lookup¹. Translation of exercises would need to happen at a different stage (when `learn-ocaml build` is run), and also rises the question of where/how the translations should be found and how we can provide the tooling for creating them.

Also, the app uses one global translation file per language, exercises should probably have their translations individually, since they are independent.

Basically, we need three parts:

- ① a way to extract the strings from the exercises to be translated and generate a template
- ①bis a way to update the translations easily when the original exercise changes (that's what guided my choice of the GNU `gettext` format for the app, because it has all the tooling for that)
- ② a way to locate the translations (when `learn-ocaml build` is run) and use them appropriately
- ③ in the app, a way to load the correct translation

③ is easy, and I guess  the (generated) exercise `json` could be duplicated for every available translation (putting them all in the same file would be possible, but result in needlessly bigger downloads). ② would'nt be too difficult either, with enumerating the available translations and generating the exercise for each of them.

① could be done using the same ppx syntax we use for the app, but with a different implementation (i.e. a `learn-ocaml build` option to (re-)generate the templates ?). Or maybe we could just set up _all_ strings for translation ?

So it's certainly doable :) , but a little more work, and we can't use the translation mechanism of the app as is. Your input on the possible choices above would be welcome.

A possibility for the files we would need to add to translate the exercise to LANG:
```
descr.html → descr.LANG.html
meta.json → ø
title.txt → title.LANG.txt
prelude.ml  prepare.ml  solution.ml  template.ml  test.ml → LANG.po
```
Note that `title.txt` and `meta.json` respectively do, and don't need translations, but that could change with the extended `meta.json` format. We could also imagine having a specification of the langs available in `meta.json` (e.g. a `lang → title` map), but I am not sure of the benefit.


¹ that lookup is fairly basic, an done in a table of translations statically defined at compile-time for now, but we intend to replace it with something more advanced at some point (e.g. fetching the translations for the selected language from a separate resource). This has little impact on the rest of the mechanics involved though.
