### ISSUE TITLE
meta-issue: learn-ocaml 0.13.0 release plan and milestones suggestions for upcoming releases

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#418]
Hi all,

Just for the record, we discussed just now with @yurug about the need to document our release plan as well as to assign milestones to PRs (there are quite a few on-going PRs that we'll merge soon!),
so we made a list of **tasks** and **PRs-to-be-merged…** w.r.t. upcoming `learn-ocaml.{0.13, 0.14, 0.15…}`

We'll close this issue as soon as learn-ocaml 0.13 is released and the suggested milestones assigned to the GitHub PRs.

(feel free to comment below for questions/remarks if need be)

## 0.13 − [direct link to the milestone](https://github.com/ocaml-sf/learn-ocaml/milestone/1) *to see pending PRs*
* [X] @yurug **Merge** (in learn-ocaml-corpus) Port to OCaml 4.12  
  https://github.com/ocaml-sf/learn-ocaml-corpus/pull/32 opened on Jul 28 by AltGr
* [x] @erikmd **Restart CI & Merge** Port to OCaml 4.12  
  https://github.com/ocaml-sf/learn-ocaml/pull/408 opened on Jul 28 by AltGr
* [x] @yurug **Doc** Partitioning codes implementing the same function  
  https://github.com/ocaml-sf/learn-ocaml/pull/287 (already merged in 0.12)
  https://github.com/ocaml-sf/learn-ocaml/pull/421
* [x] @erikmd **Fix/Improve** Make the prelude available in description page  
  https://github.com/ocaml-sf/learn-ocaml/pull/393 opened on May 12 by YoanwM
* [x] @erikmd **Dev** base64 encoding for `/description` endpoint URL  
  https://github.com/ocaml-sf/learn-ocaml/pull/423 by erikmd
* [x] @erikmd **Dev** Versioning the `learnocaml_api` API
* [x] @yurug **Rebase/Test/Merge** Add a ppx facility to test expressions  
  https://github.com/ocaml-sf/learn-ocaml/pull/403 opened on Jul 11 by lsylvestre
* [x] @erikmd **Merge(QoL)** Fix the display of utf8 characters in the code editor  
  https://github.com/ocaml-sf/learn-ocaml/pull/412 opened on Aug 11 by AltGr
* [x] @yurug **Merge(QoL)** Discourage redundant token creation from users  
  https://github.com/ocaml-sf/learn-ocaml/pull/410 opened on Jul 30 by AltGr
* [x] @erikmd **Merge(QoL)** Move the toplevel buttons to the bottom-right  
  https://github.com/ocaml-sf/learn-ocaml/pull/409 opened on Jul 30 by AltGr
* [x] @erikmd **Fix (or workaround)** compatibility issue of learn-ocaml@master with latest version of deps  
  https://github.com/ocaml-sf/learn-ocaml/issues/419 opened on Sep 15 by erikmd
  https://github.com/ocaml-sf/learn-ocaml/pull/420 by AltGr
* [x] @yurug,@erikmd **Test/Use** https://github.com/googleapis/release-please for generating released notes (on a dummy project)  
  @erikmd **Test/Use** GHA job to **auto-release build artifacts** (on a dummy project)  
  https://github.com/ocaml-sf/learn-ocaml/pull/434 by erikmd
* [x] @erikmd **Task** Document maintainer workflow in the wiki  
  → https://github.com/ocaml-sf/learn-ocaml/wiki/Checklist-for-testing-and-merging-a-PR
* [x] @erikmd **Rebase/Merge** make accessible the documentation generated by odoc  
  https://github.com/ocaml-sf/learn-ocaml/pull/404 opened on Jul 15 by EmileRolley
* [x] @erikmd **Merge** Make find_binding match annotated declarations #425  
  https://github.com/ocaml-sf/learn-ocaml/issues/424 by hferee
  https://github.com/ocaml-sf/learn-ocaml/pull/425 by hferee

(the sequel was moved to the meta-issue for 0.14.0+)

**Comment by erikmd** [comment]
I just opened #423; but postponing to 0.14 the item `Fix front-end `/description` w.r.t. static deployment` that is not critical.

**Comment by erikmd** [comment]
FYI @yurug I continued experimenting with release-please, and I confirm that when a `0.12` tag was part of the test repo, `git commit --allow-empty -m "chore: Release 0.13.0" -m "Release-As: 0.13.0"` did trigger the proper version string.

Also I believe the constraints/implied-hypothesis we noticed with this tool will be very useful to craft the `CONTRIBUTING.md` file.

I hope to finalize the release this Friday (if the `conf-libssl.3` issue that I opened in opam-repository regarding the current master CI failure on macOS can be solved).

**Comment by AltGr** [comment]
link: https://github.com/ocaml/opam-repository/issues/19676

**Comment by erikmd** [comment]
* Regarding the very last step before releasing 0.13.0, see:  
  https://github.com/ocaml-sf/learn-ocaml/pull/434

**Comment by erikmd** [comment]
Closing now this meta-issue as learn-ocaml 0.13.0 is now released on GitHub + Docker Hub + opam-repository.
