### ISSUE TITLE
meta-issue: learn-ocaml 0.13.1, 0.14.0 release plan and milestones suggestions for upcoming releases

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#437]
Hi all,

This issue aims to document the release plan as well as possible milestones for issues/PRs before setting them.

We'll close this issue as soon as learn-ocaml 0.14.1 is released.

(feel free to comment below for questions/remarks if need be)

## [0.13.1](https://github.com/ocaml-sf/learn-ocaml/milestone/1?closed=1)
* [x] @erikmd **Fix** "Actions" menubar button
  https://github.com/ocaml-sf/learn-ocaml/issues/444  
  https://github.com/ocaml-sf/learn-ocaml/pull/450
* [x] **Integrate** Pierre.Letouzey's bugfix
  https://github.com/ocaml-sf/learn-ocaml/issues/440  
  https://github.com/ocaml-sf/learn-ocaml/pull/448
* [x] @erikmd **Fix** DOCTYPE-related issue  
  https://github.com/ocaml-sf/learn-ocaml/pull/445
* [x] @erikmd Double-check GHA w.r.t. docker-push and Docker image tags convention (`v`-prefix-free)  
  https://github.com/ocaml-sf/learn-ocaml/pull/443
* [x] @AltGr Fix Progress bar for students is not displayed on a fresh repository / Fail to view student contributions  
  https://github.com/ocaml-sf/learn-ocaml/issues/314  
  https://github.com/ocaml-sf/learn-ocaml/issues/337  
  https://github.com/ocaml-sf/learn-ocaml/pull/439

## [0.14.0](https://github.com/ocaml-sf/learn-ocaml/milestone/2?closed=1)
* [x] @erikmd Reportbug(release-please): missing feature for `*.opam.locked`
* [x] @erikmd **Task** Update devs/maintainers doc regarding the constraints suggested by the release-please workflow  
  → https://github.com/ocaml-sf/learn-ocaml/wiki/Checklist-for-testing-and-merging-a-PR
* [x] @erikmd **Task** Document contributor guidelines in `CONTRIBUTING.md`, including [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/), BREAKING-CHANGE syntax, structure of a PR
  https://github.com/ocaml-sf/learn-ocaml/pull/452  
  https://github.com/ocaml-sf/learn-ocaml/pull/453
  https://github.com/ocaml-sf/learn-ocaml/pull/464
* [x] @erikmd Fix-or-Disable `learn-ocaml build -j 2`
  https://github.com/ocaml-sf/learn-ocaml/issues/414  
  https://github.com/ocaml-sf/learn-ocaml/pull/416 • Draft  
  https://github.com/ocaml-sf/learn-ocaml/pull/458 (**first commit**)
* [x] **Merge** various bug fixes
  https://github.com/ocaml-sf/learn-ocaml/pull/459  
  https://github.com/ocaml-sf/learn-ocaml/pull/461
  https://github.com/ocaml-sf/learn-ocaml/pull/455
* [x] @yurug **Rebase/Test/Merge** Offer better protections against solution overwriting  
  https://github.com/ocaml-sf/learn-ocaml/pull/372 opened on Dec 22, 2020 by yurug
* ~~**Enhance** the web UX for students clicking too much on `Sync`, avoiding empty commits. → subsumed by `#372`~~

## [0.14.1](https://github.com/ocaml-sf/learn-ocaml/milestone/6?closed=1)
* [x] @yurug / @erikmd CI: Fix linux static binaries build
* [x] @erikmd **Doc** Add more labels, inspired by PG/Coq GH repos
* [x] @erikmd **Fix/Replace** Mechanism-2
  https://github.com/ocaml-sf/learn-ocaml/issues/505
* [x] Release PRs currently integrated in master
→ https://github.com/ocaml-sf/learn-ocaml/pull/486

**Comment by erikmd** [comment]
The CI/CD builds are complete, and everything looks fine; so I updated the announcement here:
https://discuss.ocaml.org/t/ann-release-of-ocaml-sf-learn-ocaml-0-13-0/8577/6?u=erikmd

**Comment by erikmd** [comment]
Closed by #486
