### ISSUE TITLE
meta-issue: Improve user and developer documentation

### ISSUE THREAD

**Issue by erikmd** [ocaml-sf/learn-ocaml#523]
### Related user(s):

@yurug, @erikmd

### Related issue(s) or PR(s):

- #504
- #514
- #494 

### Related project scope(s):

documentation

### The problem:

* [ ] @AltGr Reply https://github.com/ocaml-sf/learn-ocaml/issues/588
* [ ] @yurug Document operational semantics of constr of `Learnocaml_api.request`
* [ ] @erikmd Better document availability of static binaries (learn-ocaml serve pas besoin switch) https://github.com/ocaml-sf/learn-ocaml/pull/504
* [ ] @erikmd Document the procedure to fetch/use macOS binaries
* [ ] @erikmd Better document markdown-to-html (feature already in master)
* [ ] @yurug Add Markdown badges in the README?
* [ ] @yurug Mention https://github.com/learn-ocaml-community/teaching-feedback in the README
* [ ] @erikmd Improve dev. documentation (e.g., mentioning direnv, magit, git prompt…)
* [ ] Address https://github.com/ocaml-sf/learn-ocaml/issues/591
* [ ] Address https://github.com/ocaml-sf/learn-ocaml/issues/524
* [ ] Address https://github.com/ocaml-sf/learn-ocaml/issues/573
* [x] @AltGr Add documentation on the teacher board  
  cf. e.g. https://github.com/ocaml-sf/learn-ocaml/issues/514#issuecomment-1412780891
